/**
 * Copies the Material Symbols (Rounded, weight 400) the Android look uses
 * into src/components/m3/symbols.ts, outline and filled, so the app draws
 * them as SVG paths without a font. Run from apps/mobile:
 *   npm pack @material-symbols/svg-400 && tar xzf material-symbols-svg-400-*.tgz
 *   node scripts/make-symbols.mjs path/to/package
 * Material Symbols are Google's, under the Apache License 2.0.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const NAMES = [
  'add', 'alternate_email', 'arrow_back', 'block', 'bookmark', 'chat_bubble', 'check', 'chevron_right', 'close',
  'content_copy', 'dark_mode', 'delete', 'download', 'edit', 'explore', 'favorite', 'flag', 'flash_on',
  'flip_camera_android', 'group', 'home', 'image', 'link', 'lock', 'logout', 'mail', 'menu', 'mode_comment',
  'more_vert', 'notifications', 'palette', 'person', 'person_add', 'photo_camera', 'play_arrow', 'public',
  'repeat', 'reply', 'search', 'settings', 'share', 'shield', 'tag', 'trending_up', 'upload', 'verified',
  'video_library', 'videocam', 'volume_off', 'volume_up', 'wallpaper', 'movie', 'shuffle', 'forum', 'visibility',
];

const dir = join(process.argv[2] ?? 'node_modules/@material-symbols/svg-400', 'rounded');
const path = async (file) => {
  const svg = await readFile(join(dir, file), 'utf8');
  return svg.match(/ d="([^"]+)"/)[1];
};

let out = `// Generated by scripts/make-symbols.mjs from Material Symbols Rounded (Apache License 2.0). Do not edit.\n`;
out += `// Paths are in Material's 960-unit box, viewBox "0 -960 960 960".\n\n`;
out += `export const SYMBOLS = {\n`;
for (const name of NAMES) {
  out += `  ${name}: [${JSON.stringify(await path(`${name}.svg`))}, ${JSON.stringify(await path(`${name}-fill.svg`))}],\n`;
}
out += `} as const;\n\nexport type SymbolName = keyof typeof SYMBOLS;\n`;
await writeFile('src/components/m3/symbols.ts', out);
console.log(`${NAMES.length} symbols`);
